


Vagrant.configure("2") do |config|
  config.vm.define "esearch" do |server|
    server.vm.box = "sbeliakou/centos"
    server.vm.hostname = "esearch"
    server.vm.box_url = "https://app.vagrantup.com/sbeliakou/boxes/centos/versions/7.6.20190810"
    server.vm.provision "shell", path: "task4.sh"
    #server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.network :private_network, ip: "192.168.56.141"   
    server.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "esearch"]
    end
  end

 
  config.vm.define "logstash" do |logstash|
    logstash.vm.box = "sbeliakou/centos"
    logstash.vm.hostname = 'logstash'
    logstash.vm.box_url = "https://app.vagrantup.com/sbeliakou/boxes/centos/versions/7.6.20190810"
    logstash.vm.provision "shell", path: "task4.sh"
    logstash.vm.network :private_network, ip: "192.168.56.142"
    logstash.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
       v.customize ["modifyvm", :id, "--name", "logstash"]
       
    end
  end
end
