$mach_quant = 2


Vagrant.configure("2") do |config|
  config.vm.define "zserver" do |server|
    server.vm.box = "sbeliakou/centos"
    server.vm.hostname = "zabbix-server"
    server.vm.box_url = "https://app.vagrantup.com/sbeliakou/boxes/centos/versions/7.6.20190810"
    server.vm.provision "shell", path: "monZSA.sh"
    #server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.network :private_network, ip: "192.168.56.141"   
    server.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "zabbix-server"]
    end
  end

 
    config.vm.define "zagent" do |zagent|
      zagent.vm.box = "sbeliakou/centos"
      zagent.vm.hostname = 'zagent'
      zagent.vm.box_url = "https://app.vagrantup.com/sbeliakou/boxes/centos/versions/7.6.20190810"
      zagent.vm.provision "shell", path: "monZSA.sh"
      zagent.vm.network :private_network, ip: "192.168.56.142"
      zagent.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
       v.customize ["modifyvm", :id, "--name", "zagent"]
       
    end
  end
end
